dist: xenial
sudo: required

language: cpp

compiler:
  - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.2-xenial -y
  - sudo apt-get update -q
  - sudo apt-get install qt512base -y

script:
  - export CXX=g++-8
  - cd ..
  - mkdir build
  - cd build
  - cmake ../gbemu
  - make -j8
  - make test
