dist: xenial

language: cpp

compiler:
  - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - ppa:beineri/opt-qt-5.11.0-xenial
    packages:
      - g++-7
      - qtbase5-dev

script:
  - export CXX=g++-7
  - cd ..
  - mkdir build
  - cd build
  - cmake ../gbemu
  - make -j8
  - make test
